# -----------------------------------------------------------------------------
# RDS Module — PostgreSQL for ConfigMirror operator persistence
#
# Creates:
#   - PostgreSQL RDS instance in isolated database subnets
#   - Security group allowing access only from EKS worker nodes
#   - KMS key for encryption at rest
#   - Random password stored in AWS SSM Parameter Store (NOT in TF state)
#   - IRSA-ready IAM policy for the operator pod to fetch the password
#
# SECURITY NOTES:
#   - RDS is in the database subnet tier — zero internet routing
#   - Password is generated randomly and stored in SSM; never in code or state
#   - Encryption at rest (KMS) and in transit (SSL enforced via parameter group)
#   - Automated backups enabled with 7-day retention
#   - Deletion protection enabled (prevents accidental destroy in prod)
#   - Multi-AZ enabled for HA (toggle via variable for dev cost saving)
# -----------------------------------------------------------------------------

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

# ---------------------------------------------------------------------------
# Random password — generated by Terraform, never committed to code
# ---------------------------------------------------------------------------
resource "random_password" "db" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
  # Exclude characters that cause issues in connection strings
  # such as @, /, \, ", '
}

# ---------------------------------------------------------------------------
# KMS Key for RDS encryption at rest
# ---------------------------------------------------------------------------
resource "aws_kms_key" "rds" {
  description             = "KMS key for RDS encryption - ${var.project_name}-${var.environment}"
  deletion_window_in_days = 7
  enable_key_rotation     = true

  tags = {
    Name = "${var.project_name}-${var.environment}-rds-kms"
  }
}

resource "aws_kms_alias" "rds" {
  name          = "alias/${var.project_name}-${var.environment}-rds"
  target_key_id = aws_kms_key.rds.key_id
}

# ---------------------------------------------------------------------------
# SSM Parameter Store — store DB credentials securely
# SECURITY: SecureString type encrypts the value using KMS.
# The operator pod will fetch this at runtime via IRSA — no hardcoded creds.
# ---------------------------------------------------------------------------
resource "aws_ssm_parameter" "db_password" {
  name        = "/${var.project_name}/${var.environment}/rds/password"
  description = "RDS master password for ${var.project_name}-${var.environment}"
  type        = "SecureString"
  value       = random_password.db.result
  key_id      = aws_kms_key.rds.arn

  tags = {
    Name = "${var.project_name}-${var.environment}-rds-password"
  }
}

resource "aws_ssm_parameter" "db_username" {
  name        = "/${var.project_name}/${var.environment}/rds/username"
  description = "RDS master username for ${var.project_name}-${var.environment}"
  type        = "SecureString"
  value       = var.db_username
  key_id      = aws_kms_key.rds.arn

  tags = {
    Name = "${var.project_name}-${var.environment}-rds-username"
  }
}

resource "aws_ssm_parameter" "db_endpoint" {
  name        = "/${var.project_name}/${var.environment}/rds/endpoint"
  description = "RDS endpoint for ${var.project_name}-${var.environment}"
  type        = "String"
  value       = aws_db_instance.this.endpoint

  tags = {
    Name = "${var.project_name}-${var.environment}-rds-endpoint"
  }
}

# ---------------------------------------------------------------------------
# Security Group — only EKS nodes can reach RDS on port 5432
# SECURITY: No 0.0.0.0/0 rules; access locked to worker node SG only
# ---------------------------------------------------------------------------
resource "aws_security_group" "rds" {
  name        = "${var.project_name}-${var.environment}-rds-sg"
  description = "Allow PostgreSQL access from EKS worker nodes only"
  vpc_id      = var.vpc_id

  ingress {
    description     = "PostgreSQL from EKS nodes only"
    from_port       = 5432
    to_port         = 5432
    protocol        = "tcp"
    security_groups = [var.eks_node_security_group_id]
  }

  egress {
    description = "Allow all outbound (for patch downloads)"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "${var.project_name}-${var.environment}-rds-sg"
  }
}

# ---------------------------------------------------------------------------
# RDS Parameter Group — enforce SSL connections
# SECURITY: rds.force_ssl=1 means any connection without SSL is rejected
# ---------------------------------------------------------------------------
resource "aws_db_parameter_group" "this" {
  name        = "${var.project_name}-${var.environment}-pg15"
  family      = "postgres15"
  description = "Custom parameter group enforcing SSL for ${var.project_name}-${var.environment}"

  parameter {
    name         = "rds.force_ssl"
    value        = "1"
    apply_method = "immediate"
  }

  parameter {
    name         = "log_connections"
    value        = "1"
    apply_method = "immediate"
  }

  parameter {
    name         = "log_disconnections"
    value        = "1"
    apply_method = "immediate"
  }

  tags = {
    Name = "${var.project_name}-${var.environment}-pg-params"
  }
}

# ---------------------------------------------------------------------------
# RDS Instance
# ---------------------------------------------------------------------------
resource "aws_db_instance" "this" {
  identifier = "${var.project_name}-${var.environment}-postgres"

  # Engine
  engine               = "postgres"
  engine_version       = "15.4"
  instance_class       = var.db_instance_class
  parameter_group_name = aws_db_parameter_group.this.name

  # Storage
  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.allocated_storage * 2 # Auto-scaling cap
  storage_type          = "gp3"
  storage_encrypted     = true  # Encryption at rest
  kms_key_id            = aws_kms_key.rds.arn

  # Credentials — pulled from random_password; NOT stored in code
  db_name  = var.db_name
  username = var.db_username
  password = random_password.db.result

  # Network — place in isolated database subnets
  db_subnet_group_name   = var.db_subnet_group_name
  vpc_security_group_ids = [aws_security_group.rds.id]
  publicly_accessible    = false  # NEVER expose RDS to the internet

  # High Availability
  multi_az = var.multi_az

  # Backups
  backup_retention_period = 7      # Keep 7 days of automated backups
  backup_window           = "03:00-04:00"
  maintenance_window      = "mon:04:00-mon:05:00"
  copy_tags_to_snapshot   = true

  # SECURITY: Prevent accidental deletion
  deletion_protection       = var.deletion_protection
  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = "${var.project_name}-${var.environment}-final-snapshot"

  # Monitoring
  monitoring_interval          = 60
  monitoring_role_arn          = aws_iam_role.rds_monitoring.arn
  performance_insights_enabled = true
  enabled_cloudwatch_logs_exports = ["postgresql", "upgrade"]

  tags = {
    Name = "${var.project_name}-${var.environment}-postgres"
  }
}

# ---------------------------------------------------------------------------
# IAM Role for RDS Enhanced Monitoring
# ---------------------------------------------------------------------------
resource "aws_iam_role" "rds_monitoring" {
  name = "${var.project_name}-${var.environment}-rds-monitoring-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "monitoring.rds.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy_attachment" "rds_monitoring" {
  role       = aws_iam_role.rds_monitoring.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}

# ---------------------------------------------------------------------------
# IRSA Policy for the ConfigMirror Operator pod
# SECURITY: The operator fetches DB credentials from SSM at runtime.
# This policy is attached to the operator's IRSA role (created in EKS module).
# The pod never sees a raw password — it reads it from SSM via this policy.
# ---------------------------------------------------------------------------
resource "aws_iam_policy" "operator_rds_access" {
  name        = "${var.project_name}-${var.environment}-operator-rds-ssm-policy"
  description = "Allows ConfigMirror operator to fetch RDS credentials from SSM"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "GetRDSCredentials"
        Effect = "Allow"
        Action = [
          "ssm:GetParameter",
          "ssm:GetParameters"
        ]
        # Scoped to ONLY the parameters for this environment
        Resource = [
          "arn:aws:ssm:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:parameter/${var.project_name}/${var.environment}/rds/*"
        ]
      },
      {
        Sid    = "DecryptSSMParameters"
        Effect = "Allow"
        Action = [
          "kms:Decrypt",
          "kms:DescribeKey"
        ]
        Resource = aws_kms_key.rds.arn
      }
    ]
  })
}
